
import Internal_Frames.Frame_jI;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
//import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableColumnModel;
//import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
//import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jcarrierpigeon.WindowPosition;
import net.sf.jtelegraph.Telegraph;
import net.sf.jtelegraph.TelegraphQueue;
import net.sf.jtelegraph.TelegraphType;
import org.jdesktop.swingx.JXSearchField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ariel Yhel Endino
 */
public final class Admin_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Panel
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    JTextField user_id = new JTextField();
    JTextField ofcr_id = new JTextField();
    JTextField budgt_ofcr_id = new JTextField();

    public Admin_Panel() {
        conn = (Connection) JavaMySqlConnection.ConnectDb();
        initComponents();
        setIcon();
        webTable1_users_info.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        webTable1_officers_info.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        webTable1_bud_ofcr_inf.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        webComboBox1_offcr_stat.setEnabled(false);
        webComboBox2_bdget_ofcr_stat.setEnabled(false);
        webButton1_update.setEnabled(false);
        webButton1_update.setToolTipText("Select User from table to update");
        webButton1_update_officer.setEnabled(false);
        webButton1_update_officer.setToolTipText("Select Officer from table to update");
        webButton5_update_bdg_off.setEnabled(false);
        webButton5_update_bdg_off.setToolTipText("Select Budget Officer from table to update");
        webTable1_users_info.setToolTipText("Select (Click) User(s) to Update");
        webTable1_officers_info.setToolTipText("Select (Click) Officer(s) to Update");
        webTable1_bud_ofcr_inf.setToolTipText("Select (Click) Budget Officer(s) to Update");
        Users_information();
        Officers_Information();
        Budget_Officer_Information();
        Table_Pane_Users();
        Table_Pane_Officers();
        Table_Pane_Budget_Officer_Inoformation();
        Testingan_tanaw();
        Testingan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jXTextArea1 = new org.jdesktop.swingx.JXTextArea();
        webTabbedPane1 = new com.alee.laf.tabbedpane.WebTabbedPane();
        webPanel1 = new com.alee.laf.panel.WebPanel();
        webTextField2_minit = new com.alee.laf.text.WebTextField();
        webTextField3_lname = new com.alee.laf.text.WebTextField();
        webTextField4_username = new com.alee.laf.text.WebTextField();
        webTextField5_password = new com.alee.laf.text.WebTextField();
        webButton1_update = new com.alee.laf.button.WebButton();
        webPanel3 = new com.alee.laf.panel.WebPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        webTable1_users_info = new com.alee.laf.table.WebTable();
        webComboBox1_status = new com.alee.laf.combobox.WebComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jXSearchField1_search = new org.jdesktop.swingx.JXSearchField();
        webButton3_user_cancel = new com.alee.laf.button.WebButton();
        webTextField1_name = new com.alee.laf.text.WebTextField();
        webPanel2 = new com.alee.laf.panel.WebPanel();
        webPanel6 = new com.alee.laf.panel.WebPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        webTable1_officers_info = new com.alee.laf.table.WebTable();
        webTextField1_officer_fullname = new com.alee.laf.text.WebTextField();
        webTextField2_officer_pos = new com.alee.laf.text.WebTextField();
        webButton1_update_officer = new com.alee.laf.button.WebButton();
        webButton3_cancel = new com.alee.laf.button.WebButton();
        webButton4_add_ofcr = new com.alee.laf.button.WebButton();
        webComboBox1_offcr_stat = new com.alee.laf.combobox.WebComboBox();
        webPanel7 = new com.alee.laf.panel.WebPanel();
        webTextField1_bdgt_ofcr_fname = new com.alee.laf.text.WebTextField();
        webTextField2_bdgt_ofcr_pos = new com.alee.laf.text.WebTextField();
        webButton4_add_bdget_off = new com.alee.laf.button.WebButton();
        webButton5_update_bdg_off = new com.alee.laf.button.WebButton();
        webButton6_cancel1 = new com.alee.laf.button.WebButton();
        webPanel8 = new com.alee.laf.panel.WebPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        webTable1_bud_ofcr_inf = new com.alee.laf.table.WebTable();
        webComboBox2_bdget_ofcr_stat = new com.alee.laf.combobox.WebComboBox();
        webPanel4 = new com.alee.laf.panel.WebPanel();
        webLabel5_message = new com.alee.laf.label.WebLabel();
        webLabel5_new = new com.alee.laf.label.WebLabel();
        webButton1 = new com.alee.laf.button.WebButton();
        webDesktopPane1 = new com.alee.laf.desktoppane.WebDesktopPane();
        webPanel5 = new com.alee.laf.panel.WebPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testingan = new com.alee.laf.table.WebTable();
        edit = new com.alee.laf.button.WebButton();
        webLabel1 = new com.alee.laf.label.WebLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();

        jXTextArea1.setColumns(20);
        jXTextArea1.setRows(5);
        jScrollPane3.setViewportView(jXTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Panel"); // NOI18N
        setBackground(new java.awt.Color(255, 204, 204));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        webTabbedPane1.setToolTipText("");
        webTabbedPane1.setBottomBg(new java.awt.Color(255, 255, 0));
        webTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webTabbedPane1.setInheritsPopupMenu(true);
        webTabbedPane1.setName(""); // NOI18N
        webTabbedPane1.setRotateTabInsets(true);
        webTabbedPane1.setSelectedBottomBg(new java.awt.Color(51, 255, 255));
        webTabbedPane1.setSelectedTopBg(new java.awt.Color(204, 204, 204));
        webTabbedPane1.setTabOverlay(5);
        webTabbedPane1.setTopBg(new java.awt.Color(153, 255, 204));

        webTextField2_minit.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField2_minit.setInputPrompt("Field for Middle Initial");
        webTextField2_minit.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 10)); // NOI18N

        webTextField3_lname.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField3_lname.setInputPrompt("Field for Lastname");
        webTextField3_lname.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 10)); // NOI18N

        webTextField4_username.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField4_username.setInputPrompt("Field for Username");
        webTextField4_username.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 10)); // NOI18N

        webTextField5_password.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField5_password.setInputPrompt("Field for Password");
        webTextField5_password.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 10)); // NOI18N

        webButton1_update.setBackground(new java.awt.Color(204, 204, 255));
        webButton1_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        webButton1_update.setText("UPDATE ACCOUNT");
        webButton1_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webButton1_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1_updateActionPerformed(evt);
            }
        });

        webTable1_users_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        webTable1_users_info.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        webTable1_users_info.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTable1_users_info.setRowHeight(20);
        webTable1_users_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webTable1_users_infoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(webTable1_users_info);

        webPanel3.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        webComboBox1_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive" }));
        webComboBox1_status.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N

        jLabel1.setText("Firstname");

        jLabel2.setText("Middle Initial");

        jLabel3.setText("Lastname");

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        jLabel6.setText("Status");

        jXSearchField1_search.setToolTipText("Search User");
        jXSearchField1_search.setLayoutStyle(org.jdesktop.swingx.JXSearchField.LayoutStyle.MAC);
        jXSearchField1_search.setPrompt("Search User");
        jXSearchField1_search.setPromptBackround(new java.awt.Color(255, 255, 204));
        jXSearchField1_search.setPromptFontStyle(new java.lang.Integer(3));
        jXSearchField1_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jXSearchField1_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jXSearchField1_searchKeyReleased(evt);
            }
        });

        webButton3_user_cancel.setText("CANCEL");
        webButton3_user_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webButton3_user_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton3_user_cancelActionPerformed(evt);
            }
        });

        webTextField1_name.setInputPrompt("Field for Firstname");
        webTextField1_name.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 10)); // NOI18N

        javax.swing.GroupLayout webPanel1Layout = new javax.swing.GroupLayout(webPanel1);
        webPanel1.setLayout(webPanel1Layout);
        webPanel1Layout.setHorizontalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addComponent(webButton1_update, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(webButton3_user_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(webTextField1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(webComboBox1_status, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(webTextField2_minit, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(webTextField3_lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(webTextField4_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(webTextField5_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXSearchField1_search, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        webPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {webButton1_update, webButton3_user_cancel, webTextField2_minit, webTextField3_lname, webTextField4_username, webTextField5_password});

        webPanel1Layout.setVerticalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, webPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(webComboBox1_status, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(webTextField1_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(webTextField2_minit, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(webTextField3_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(webTextField4_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(webTextField5_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webButton3_user_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webButton1_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(webPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXSearchField1_search, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        webPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {webTextField2_minit, webTextField4_username, webTextField5_password});

        webPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {webButton1_update, webButton3_user_cancel});

        webTabbedPane1.addTab("Update Users Account", webPanel1);

        webTable1_officers_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        webTable1_officers_info.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        webTable1_officers_info.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTable1_officers_info.setRowHeight(20);
        webTable1_officers_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webTable1_officers_infoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(webTable1_officers_info);

        webPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        webTextField1_officer_fullname.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField1_officer_fullname.setInputPrompt("Officer Fullname");
        webTextField1_officer_fullname.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N

        webTextField2_officer_pos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField2_officer_pos.setInputPrompt("Officer Position");
        webTextField2_officer_pos.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N

        webButton1_update_officer.setText("UPDATE OFFICER");
        webButton1_update_officer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webButton1_update_officer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1_update_officerActionPerformed(evt);
            }
        });

        webButton3_cancel.setText("CANCEL");
        webButton3_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webButton3_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton3_cancelActionPerformed(evt);
            }
        });

        webButton4_add_ofcr.setText("ADD OFFICER");
        webButton4_add_ofcr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webButton4_add_ofcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton4_add_ofcrActionPerformed(evt);
            }
        });

        webComboBox1_offcr_stat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "STATUS", "Active", "Inactive" }));
        webComboBox1_offcr_stat.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N

        javax.swing.GroupLayout webPanel2Layout = new javax.swing.GroupLayout(webPanel2);
        webPanel2.setLayout(webPanel2Layout);
        webPanel2Layout.setHorizontalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(webTextField2_officer_pos, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(webTextField1_officer_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addComponent(webComboBox1_offcr_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(webButton3_cancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(webButton1_update_officer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(webButton4_add_ofcr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addComponent(webPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );

        webPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {webTextField1_officer_fullname, webTextField2_officer_pos});

        webPanel2Layout.setVerticalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(webTextField1_officer_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(webTextField2_officer_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webComboBox1_offcr_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(webButton4_add_ofcr, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(webButton1_update_officer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(webButton3_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, webPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(webPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        webPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {webTextField1_officer_fullname, webTextField2_officer_pos});

        webTabbedPane1.addTab("Add Officer / Update Officer", webPanel2);

        webTextField1_bdgt_ofcr_fname.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField1_bdgt_ofcr_fname.setInputPrompt("Budget Officer Fullname");
        webTextField1_bdgt_ofcr_fname.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N

        webTextField2_bdgt_ofcr_pos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField2_bdgt_ofcr_pos.setInputPrompt("Budget Officer Position");
        webTextField2_bdgt_ofcr_pos.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N

        webButton4_add_bdget_off.setText("ADD OFFICER");
        webButton4_add_bdget_off.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webButton4_add_bdget_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton4_add_bdget_offActionPerformed(evt);
            }
        });

        webButton5_update_bdg_off.setText("UPDATE OFFICER");
        webButton5_update_bdg_off.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webButton5_update_bdg_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton5_update_bdg_offActionPerformed(evt);
            }
        });

        webButton6_cancel1.setText("CANCEL");
        webButton6_cancel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webButton6_cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton6_cancel1ActionPerformed(evt);
            }
        });

        webTable1_bud_ofcr_inf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        webTable1_bud_ofcr_inf.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        webTable1_bud_ofcr_inf.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTable1_bud_ofcr_inf.setRowHeight(20);
        webTable1_bud_ofcr_inf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webTable1_bud_ofcr_infMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(webTable1_bud_ofcr_inf);

        webPanel8.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        webComboBox2_bdget_ofcr_stat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "STATUS", "Active", "Inactive" }));
        webComboBox2_bdget_ofcr_stat.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N

        javax.swing.GroupLayout webPanel7Layout = new javax.swing.GroupLayout(webPanel7);
        webPanel7.setLayout(webPanel7Layout);
        webPanel7Layout.setHorizontalGroup(
            webPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(webPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(webPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(webTextField1_bdgt_ofcr_fname, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(webTextField2_bdgt_ofcr_pos, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(webComboBox2_bdget_ofcr_stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(webPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(webButton6_cancel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(webButton5_update_bdg_off, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(webButton4_add_bdget_off, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addComponent(webPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
        webPanel7Layout.setVerticalGroup(
            webPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(webTextField1_bdgt_ofcr_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(webTextField2_bdgt_ofcr_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webComboBox2_bdget_ofcr_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(webButton4_add_bdget_off, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(webButton5_update_bdg_off, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(webButton6_cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, webPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(webPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        webPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {webTextField1_bdgt_ofcr_fname, webTextField2_bdgt_ofcr_pos});

        webTabbedPane1.addTab("Add Budget Officer / Update Budget Officer", webPanel7);

        webLabel5_message.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        webLabel5_new.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        webButton1.setText("FUNDS");
        webButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1ActionPerformed(evt);
            }
        });

        webDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        webPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        testingan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        testingan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testinganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(testingan);

        webPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        webDesktopPane1.add(webPanel5);
        webPanel5.setBounds(10, 10, 550, 370);

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout webPanel4Layout = new javax.swing.GroupLayout(webPanel4);
        webPanel4.setLayout(webPanel4Layout);
        webPanel4Layout.setHorizontalGroup(
            webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(webButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(webDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webLabel5_message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel5_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        webPanel4Layout.setVerticalGroup(
            webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel4Layout.createSequentialGroup()
                .addGroup(webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(webButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(webPanel4Layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(webLabel5_message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(webPanel4Layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(webLabel5_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(webPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(webDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );

        webTabbedPane1.addTab("Change Master Key", webPanel4);

        getContentPane().add(webTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 870, 460));

        webLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Admin_Panel.png"))); // NOI18N
        getContentPane().add(webLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 930, 560));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(0, 204, 204));
        jMenuBar1.setInheritsPopupMenu(true);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Settings_Icon.png"))); // NOI18N

        jMenuItem1.setText("My Profile");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("View all logs");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Logout");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User-Administrator-Green-icon.png"))); // NOI18N
        jMenu3_admin.setEnabled(false);
        jMenu3_admin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu3_admin);

        jMenu14.setEnabled(false);
        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(920, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void webButton4_add_ofcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton4_add_ofcrActionPerformed
        String ofcr_fullname = webTextField1_officer_fullname.getText();
        String ofcr_position = webTextField2_officer_pos.getText();
        if (ofcr_fullname.isEmpty() || ofcr_position.isEmpty()) {
            // JOptionPane.showMessageDialog(null, "Please fill the fields", "System Message", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "<html>"
                    + "<body style='color:red;font-size:10px'>"
                    + "<b>Please fill all the fields.</b>"
                    + "</body>"
                    + "</html>", "System Message", JOptionPane.ERROR_MESSAGE);
        } else {
            String SQL = "Insert into officers_and_position (fullname,position,date_added) values (?,?,now())";
            try {
                pst = (PreparedStatement) conn.prepareStatement(SQL);
                pst.setString(1, webTextField1_officer_fullname.getText());
                pst.setString(2, webTextField2_officer_pos.getText());
                pst.execute();
                Telegraph tel = new Telegraph("Message", "<html>"
                        + "<body style='color:green;font-size:13px'>"
                        + "<b> New Officer Added Successfully..."
                        + "</b>"
                        + "</body>"
                        + "</html>", TelegraphType.NOTIFICATION_ADD, WindowPosition.TOPRIGHT, 1500);
                TelegraphQueue TQ = new TelegraphQueue();
                TQ.add(tel);
                Table_Pane_Officers();
                Officers_Information();
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(null, "This Officer is already added", "Warning", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(null, "<html>"
                        + "<body style='color:red;font-size:10px'>"
                        + "<b>This Officer is already Registered.</b>"
                        + "</body>"
                        + "</html>", "System Message", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_webButton4_add_ofcrActionPerformed

    private void webButton1_update_officerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1_update_officerActionPerformed
        String SQL_Update = "Update officers_and_position set fullname='" + webTextField1_officer_fullname.getText() + "', position ='" + webTextField2_officer_pos.getText() + "',status='" + webComboBox1_offcr_stat.getSelectedItem().toString() + "'where id ='" + ofcr_id.getText() + "'";
        try {
            pst = (PreparedStatement) conn.prepareStatement(SQL_Update);
            pst.execute();
            Telegraph tel = new Telegraph("Message", "<html>"
                    + "<body style='color:green;font-size:13px'>"
                    + "<b> Officer successfully updated!"
                    + "</b>"
                    + "</body>"
                    + "</html>", TelegraphType.FILE_EDIT, WindowPosition.TOPRIGHT, 1500);
            TelegraphQueue TQ = new TelegraphQueue();
            TQ.add(tel);
            Update_Officer_Account_Logs();
            Table_Pane_Officers();
            Officers_Information();
            webTextField1_officer_fullname.setText("");
            webTextField2_officer_pos.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_webButton1_update_officerActionPerformed

    private void webTable1_officers_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webTable1_officers_infoMouseClicked

        int row = webTable1_officers_info.getSelectedRow();
        String Table_Clickid = (webTable1_officers_info.getModel().getValueAt(row, 0).toString());
        String Table_Click = (webTable1_officers_info.getModel().getValueAt(row, 1).toString());
        String Table_Click1 = (webTable1_officers_info.getModel().getValueAt(row, 2).toString());
        String Table_Click2 = (webTable1_officers_info.getModel().getValueAt(row, 3).toString());

        ofcr_id.setText(Table_Clickid);
        webTextField1_officer_fullname.setText(Table_Click);
        webTextField2_officer_pos.setText(Table_Click1);
        webComboBox1_offcr_stat.setEnabled(true);
        webComboBox1_offcr_stat.setSelectedItem(Table_Click2);
        webButton1_update_officer.setEnabled(true);
        webButton4_add_ofcr.setEnabled(false);
        webButton1_update_officer.setToolTipText(null);


    }//GEN-LAST:event_webTable1_officers_infoMouseClicked

    private void jXSearchField1_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXSearchField1_searchKeyReleased
        try {

            String sql = "select Firstname ,Middle_Initial as 'Minit',Lastname,Username,"
                    + "Password,user_status as 'Status'"
                    + " from users_table where user_status "
                    + "like '%" + jXSearchField1_search.getText() + "%' Or Firstname like '%"
                    + jXSearchField1_search.getText() + "%' OR Lastname like '%" + jXSearchField1_search.getText()
                    + "%' OR Username like '%" + jXSearchField1_search.getText() + "%'";

            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String name = rs.getString("Firstname");
                jXSearchField1_search.setRecentSearchesSaveKey(name);
                jXSearchField1_search.setUseSeperatePopupButton(true);
                jXSearchField1_search.setSearchMode(JXSearchField.SearchMode.INSTANT);
                webTable1_users_info.setModel(DbUtils.resultSetToTableModel(rs));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jXSearchField1_searchKeyReleased

    private void jXSearchField1_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXSearchField1_searchKeyPressed

    }//GEN-LAST:event_jXSearchField1_searchKeyPressed

    private void webButton1_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1_updateActionPerformed

        if (webTextField4_username.getText().length() == 2 || webTextField4_username.getText().length() == 3
                || webTextField4_username.getText().length() == 4) {
            JOptionPane.showMessageDialog(null, "<html>"
                    + "<body style='color:red;font-size:10px'>"
                    + "<b>Username is atleast 5 characters.</b>"
                    + "</body>"
                    + "</html>", "System Message", JOptionPane.ERROR_MESSAGE);
        } else {
            String SQL_Update_User = "Update users_table set firstname ='" + webTextField1_name.getText() + "',Middle_Initial = '" + webTextField2_minit.getText() + "',Lastname ='" + webTextField3_lname.getText() + "',Username = '" + webTextField4_username.getText() + "', Password = '" + webTextField5_password.getText() + "',user_status = '" + webComboBox1_status.getSelectedItem().toString() + "'where reg_id ='" + user_id.getText() + "'";
            try {
                //String sql = "Update users_table set firstname ='" + webTextField1_name.getText() + "', Middle_Initial ='" + webTextField2_minit.getText() + "', Lastname ='" + webTextField3_lname.getText() + "', Username ='" + webTextField4_username.getText() + "', Password ='" + webTextField5_password.getText() + "',user_status ='" + webComboBox1_status.getSelectedItem().toString() + "'where firstname ='" + webTextField1_name.getText() + "'";
                pst = (PreparedStatement) conn.prepareStatement(SQL_Update_User);
                pst.execute();
                Telegraph tel = new Telegraph("Message", "<html>"
                        + "<body style='color:green;font-size:13px'>"
                        + "<b> Data successfully updated!"
                        + "</b>"
                        + "</body>"
                        + "</html>", TelegraphType.FILE_EDIT, WindowPosition.TOPRIGHT, 1500);
                TelegraphQueue TQ = new TelegraphQueue();
                TQ.add(tel);
                Update_User_Account_Logs();
                webTextField1_name.setText("");
                webTextField2_minit.setText("");
                webTextField3_lname.setText("");
                webTextField4_username.setText("");
                webTextField5_password.setText("");
                webButton1_update.setEnabled(false);
                Table_Pane_Users();
                Users_information();

            } catch (Exception e) {
                e.printStackTrace();

            }
        }
    }//GEN-LAST:event_webButton1_updateActionPerformed

    private void webButton4_add_bdget_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton4_add_bdget_offActionPerformed
        String budgt_ofcr_fullname = webTextField1_bdgt_ofcr_fname.getText();
        String budgt_ofcr_position = webTextField2_bdgt_ofcr_pos.getText();
        if (budgt_ofcr_fullname.isEmpty() || budgt_ofcr_position.isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Plese fill all the fields", "System Message", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "<html>"
                    + "<body style='color:red;font-size:10px'>"
                    + "<b>Please fill all the fields.</b>"
                    + "</body>"
                    + "</html>", "System Message", JOptionPane.ERROR_MESSAGE);
        } else {
            String SQL_Insert_Budget_Officer = "Insert into budget_officer_and_position (Fullname,Position,date_added)"
                    + "values (?,?,now())";
            try {
                pst = (PreparedStatement) conn.prepareStatement(SQL_Insert_Budget_Officer);
                pst.setString(1, webTextField1_bdgt_ofcr_fname.getText());
                pst.setString(2, webTextField2_bdgt_ofcr_pos.getText());
                pst.execute();
                Telegraph tel = new Telegraph("Message", "<html>"
                        + "<body style='color:green;font-size:13px'>"
                        + "<b> Budget Officer Successfully Added..."
                        + "</b>"
                        + "</body>"
                        + "</html>", TelegraphType.NOTIFICATION_DONE, WindowPosition.TOPRIGHT, 1500);
                TelegraphQueue TQ = new TelegraphQueue();
                TQ.add(tel);
                Table_Pane_Budget_Officer_Inoformation();
                Budget_Officer_Information();
                webTextField1_bdgt_ofcr_fname.setText("");
                webTextField2_bdgt_ofcr_pos.setText("");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_webButton4_add_bdget_offActionPerformed

    private void webTable1_bud_ofcr_infMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webTable1_bud_ofcr_infMouseClicked
        int row = webTable1_bud_ofcr_inf.getSelectedRow();
        String Table_Clickid = (webTable1_bud_ofcr_inf.getModel().getValueAt(row, 0).toString());
        String Table_Click = (webTable1_bud_ofcr_inf.getModel().getValueAt(row, 1).toString());
        String Table_Click1 = (webTable1_bud_ofcr_inf.getModel().getValueAt(row, 2).toString());
        String Table_Click2 = (webTable1_bud_ofcr_inf.getModel().getValueAt(row, 3).toString());

        budgt_ofcr_id.setText(Table_Clickid);
        webTextField1_bdgt_ofcr_fname.setText(Table_Click);
        webTextField2_bdgt_ofcr_pos.setText(Table_Click1);
        webComboBox2_bdget_ofcr_stat.setEnabled(true);
        webComboBox2_bdget_ofcr_stat.setSelectedItem(Table_Click2);
        webButton5_update_bdg_off.setEnabled(true);
        webButton4_add_bdget_off.setEnabled(false);
        webButton5_update_bdg_off.setToolTipText(null);

        /*TableModel model = webTable1_bud_ofcr_inf.getModel();
         int[] indexs = webTable1_bud_ofcr_inf.getSelectedRows();
         Object[] row_w = new Object[5];

         DefaultTableModel model2 = (DefaultTableModel) webTable1.getModel();

         for (int i = 0; i < indexs.length; i++) {
         row_w[0] = model.getValueAt(indexs[i], 0);

         row_w[1] = model.getValueAt(indexs[i], 1);

         row_w[2] = model.getValueAt(indexs[i], 2);

         row_w[3] = model.getValueAt(indexs[i], 3);

         row_w[4] = model.getValueAt(indexs[i], 4);
            
         //row_w[5] = model.getValueAt(indexs[i], 5);


         model2.addRow(row_w);

         }*/
    }//GEN-LAST:event_webTable1_bud_ofcr_infMouseClicked

    private void webButton3_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton3_cancelActionPerformed
        webTextField1_officer_fullname.setText("");
        webTextField2_officer_pos.setText("");
        webButton1_update_officer.setEnabled(false);
        webButton4_add_ofcr.setEnabled(true);
        webComboBox1_offcr_stat.setEnabled(false);
        webButton1_update_officer.setToolTipText("Select Officer from table to update");
    }//GEN-LAST:event_webButton3_cancelActionPerformed

    private void webButton6_cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton6_cancel1ActionPerformed
        webTextField1_bdgt_ofcr_fname.setText("");
        webTextField2_bdgt_ofcr_pos.setText("");
        webButton5_update_bdg_off.setEnabled(false);
        webButton4_add_bdget_off.setEnabled(true);
        webComboBox2_bdget_ofcr_stat.setEnabled(false);
        webButton5_update_bdg_off.setToolTipText("Select Budget Officer from table to update");
    }//GEN-LAST:event_webButton6_cancel1ActionPerformed

    private void webButton5_update_bdg_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton5_update_bdg_offActionPerformed
        String SQL_Update = "Update budget_officer_and_position set fullname='" + webTextField1_bdgt_ofcr_fname.getText() + "', position ='" + webTextField2_bdgt_ofcr_pos.getText() + "',status='" + webComboBox2_bdget_ofcr_stat.getSelectedItem().toString() + "'where id ='" + budgt_ofcr_id.getText() + "'";
        try {
            pst = (PreparedStatement) conn.prepareStatement(SQL_Update);
            pst.execute();
            Telegraph tel = new Telegraph("Message", "<html>"
                    + "<body style='color:green;font-size:13px'>"
                    + "<b> Officer successfully updated!"
                    + "</b>"
                    + "</body>"
                    + "</html>", TelegraphType.FILE_EDIT, WindowPosition.TOPRIGHT, 1500);
            TelegraphQueue TQ = new TelegraphQueue();
            TQ.add(tel);
            Update_Budget_Officer_Account_Logs();
            Table_Pane_Budget_Officer_Inoformation();
            Budget_Officer_Information();
            webTextField1_officer_fullname.setText("");
            webTextField2_officer_pos.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_webButton5_update_bdg_offActionPerformed

    private void webButton3_user_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton3_user_cancelActionPerformed
        webTextField1_name.setText("");
        webTextField2_minit.setText("");
        webTextField3_lname.setText("");
        webTextField4_username.setText("");
        webTextField5_password.setText("");
        webComboBox1_status.setSelectedItem("Status");
        webButton1_update.setEnabled(false);
        webButton1_update.setToolTipText("Select User from table to update");
    }//GEN-LAST:event_webButton3_user_cancelActionPerformed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        Admin_Logs al = new Admin_Logs();
        al.setVisible(true);
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        Telegraph tel = new Telegraph("Message", "<html>"
                + "<body style='color:green;font-size:13px'>"
                + "<b> Successfully Logout..."
                + "</b>"
                + "</body>"
                + "</html>", TelegraphType.NOTIFICATION_DONE, WindowPosition.TOPRIGHT, 1500);
        TelegraphQueue TQ = new TelegraphQueue();
        TQ.add(tel);
        Logout();
        System_Admin_and_User_Login saaul = new System_Admin_and_User_Login();
        saaul.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void webButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1ActionPerformed
        Funds f = new Funds();
        f.setVisible(true);
    }//GEN-LAST:event_webButton1ActionPerformed

    private void webTable1_users_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webTable1_users_infoMouseClicked
        int row = webTable1_users_info.getSelectedRow();
        String Table_Clickid = (webTable1_users_info.getModel().getValueAt(row, 0).toString());
        String Table_Click = (webTable1_users_info.getModel().getValueAt(row, 1).toString());
        String Table_Click1 = (webTable1_users_info.getModel().getValueAt(row, 2).toString());
        String Table_Click2 = (webTable1_users_info.getModel().getValueAt(row, 3).toString());
        String Table_Click3 = (webTable1_users_info.getModel().getValueAt(row, 4).toString());
        String Table_Click4 = (webTable1_users_info.getModel().getValueAt(row, 5).toString());
        String Table_Click5 = (webTable1_users_info.getModel().getValueAt(row, 6).toString());

        user_id.setText(Table_Clickid);
        webTextField1_name.setText(Table_Click);
        webTextField2_minit.setText(Table_Click1);
        webTextField3_lname.setText(Table_Click2);
        webTextField4_username.setText(Table_Click3);
        webTextField5_password.setText(Table_Click4);
        webComboBox1_status.setSelectedItem(Table_Click5);
        webButton1_update.setEnabled(true);
        webButton1_update.setToolTipText(null);
    }//GEN-LAST:event_webTable1_users_infoMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed

        //Component add = this.webDesktopPane1.add(jframe);
        //.setVisible(true);
        //add.setVisible(true);
        try {
            if (jframe == null || jframe.isClosed()) {
                jframe = new Frame_jI();
                this.webDesktopPane1.add(jframe);
                jframe.setVisible(true);
                jframe.setSelected(true);

            } else {
                if (jframe.isIcon()) {
                    this.jframe.setIcon(true);
                }
                jframe.setSelected(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editActionPerformed

    private void testinganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testinganMouseClicked

        int row = testingan.getSelectedRow();
        //String Table_Clickid = (webTable1_bud_ofcr_inf.getModel().getValueAt(row, 0).toString());
        String Table_Click = (webTable1_bud_ofcr_inf.getModel().getValueAt(row, 1).toString());
        //String Table_Click1 = (webTable1_bud_ofcr_inf.getModel().getValueAt(row, 2).toString());
        //String Table_Click2 = (webTable1_bud_ofcr_inf.getModel().getValueAt(row, 3).toString());
        Frame_jI.try1.setText(Table_Click);
        //budgt_ofcr_id.setText(Table_Clickid);
        //webTextField1_bdgt_ofcr_fname.setText(Table_Click);
        //webTextField2_bdgt_ofcr_pos.setText(Table_Click1);
    }//GEN-LAST:event_testinganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    public static final javax.swing.JMenu jMenu3_admin = new javax.swing.JMenu();
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private org.jdesktop.swingx.JXSearchField jXSearchField1_search;
    private org.jdesktop.swingx.JXTextArea jXTextArea1;
    private com.alee.laf.table.WebTable testingan;
    private com.alee.laf.button.WebButton webButton1;
    private com.alee.laf.button.WebButton webButton1_update;
    private com.alee.laf.button.WebButton webButton1_update_officer;
    private com.alee.laf.button.WebButton webButton3_cancel;
    private com.alee.laf.button.WebButton webButton3_user_cancel;
    private com.alee.laf.button.WebButton webButton4_add_bdget_off;
    private com.alee.laf.button.WebButton webButton4_add_ofcr;
    private com.alee.laf.button.WebButton webButton5_update_bdg_off;
    private com.alee.laf.button.WebButton webButton6_cancel1;
    private com.alee.laf.combobox.WebComboBox webComboBox1_offcr_stat;
    private com.alee.laf.combobox.WebComboBox webComboBox1_status;
    private com.alee.laf.combobox.WebComboBox webComboBox2_bdget_ofcr_stat;
    private com.alee.laf.desktoppane.WebDesktopPane webDesktopPane1;
    private com.alee.laf.label.WebLabel webLabel1;
    private com.alee.laf.label.WebLabel webLabel5_message;
    private com.alee.laf.label.WebLabel webLabel5_new;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.panel.WebPanel webPanel2;
    private com.alee.laf.panel.WebPanel webPanel3;
    private com.alee.laf.panel.WebPanel webPanel4;
    private com.alee.laf.panel.WebPanel webPanel5;
    private com.alee.laf.panel.WebPanel webPanel6;
    private com.alee.laf.panel.WebPanel webPanel7;
    private com.alee.laf.panel.WebPanel webPanel8;
    private com.alee.laf.tabbedpane.WebTabbedPane webTabbedPane1;
    private com.alee.laf.table.WebTable webTable1_bud_ofcr_inf;
    private com.alee.laf.table.WebTable webTable1_officers_info;
    private com.alee.laf.table.WebTable webTable1_users_info;
    private com.alee.laf.text.WebTextField webTextField1_bdgt_ofcr_fname;
    private com.alee.laf.text.WebTextField webTextField1_name;
    private com.alee.laf.text.WebTextField webTextField1_officer_fullname;
    private com.alee.laf.text.WebTextField webTextField2_bdgt_ofcr_pos;
    private com.alee.laf.text.WebTextField webTextField2_minit;
    private com.alee.laf.text.WebTextField webTextField2_officer_pos;
    private com.alee.laf.text.WebTextField webTextField3_lname;
    private com.alee.laf.text.WebTextField webTextField4_username;
    private com.alee.laf.text.WebTextField webTextField5_password;
    // End of variables declaration//GEN-END:variables
    private JInternalFrame jframe;

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/tatelogo.png")));
    }

    public void Testingan() {

        for (int i = 0; i < testingan.getColumnCount(); i++) {
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) testingan.getColumnModel();
            TableColumn col = colModel.getColumn(i);
            int width = 0;

            TableCellRenderer renderer = col.getHeaderRenderer();
            for (int r = 0; r < testingan.getRowCount(); r++) {
                renderer = testingan.getCellRenderer(r, i);
                Component comp = renderer.getTableCellRendererComponent(testingan, testingan.getValueAt(r, i),
                        false, false, r, i);
                width = Math.max(width, comp.getPreferredSize().width);
            }

            col.setPreferredWidth(width + 120);

        }
    }

    public void Table_Pane_Users() {

        for (int i = 0; i < webTable1_users_info.getColumnCount(); i++) {
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) webTable1_users_info.getColumnModel();
            TableColumn col = colModel.getColumn(i);
            int width = 0;

            TableCellRenderer renderer = col.getHeaderRenderer();
            for (int r = 0; r < webTable1_users_info.getRowCount(); r++) {
                renderer = webTable1_users_info.getCellRenderer(r, i);
                Component comp = renderer.getTableCellRendererComponent(webTable1_users_info, webTable1_users_info.getValueAt(r, i),
                        false, false, r, i);
                width = Math.max(width, comp.getPreferredSize().width);
            }

            col.setPreferredWidth(width + 120);

        }
    }

    public void Table_Pane_Officers() {

        for (int i = 0; i < webTable1_officers_info.getColumnCount(); i++) {
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) webTable1_officers_info.getColumnModel();
            TableColumn col = colModel.getColumn(i);
            int width = 0;

            TableCellRenderer renderer = col.getHeaderRenderer();
            for (int r = 0; r < webTable1_officers_info.getRowCount(); r++) {
                renderer = webTable1_officers_info.getCellRenderer(r, i);
                Component comp = renderer.getTableCellRendererComponent(webTable1_officers_info, webTable1_officers_info.getValueAt(r, i),
                        false, false, r, i);
                width = Math.max(width, comp.getPreferredSize().width);
            }

            col.setPreferredWidth(width + 120);

        }

    }

    public void Table_Pane_Budget_Officer_Inoformation() {

        for (int i = 0; i < webTable1_bud_ofcr_inf.getColumnCount(); i++) {
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) webTable1_bud_ofcr_inf.getColumnModel();
            TableColumn col = colModel.getColumn(i);
            int width = 0;

            TableCellRenderer renderer = col.getHeaderRenderer();
            for (int r = 0; r < webTable1_bud_ofcr_inf.getRowCount(); r++) {
                renderer = webTable1_users_info.getCellRenderer(r, i);
                Component comp = renderer.getTableCellRendererComponent(webTable1_bud_ofcr_inf, webTable1_bud_ofcr_inf.getValueAt(r, i),
                        false, false, r, i);
                width = Math.max(width, comp.getPreferredSize().width);
            }

            col.setPreferredWidth(width + 120);

        }
    }

    private void Users_information() {
        try {
            String sql = "select reg_id as 'ID', firstname, Middle_Initial as 'Minit',"
                    + " Lastname ,Username as 'Username', Password as 'Password', Privileges, user_status as 'Status' from users_table";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            webTable1_users_info.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    private void Officers_Information() {
        try {
            String sql = "select id as 'ID', fullname as 'Fullname', position as 'Position', "
                    + "date_added as 'Date Added', status as 'Status' from officers_and_position";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            webTable1_officers_info.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    
    
    
    
    
    
    
    private void Testingan_tanaw() {
        try {
            String sql = "select id as 'ID', Fullname as 'Fullname', Position as 'Position', date_added as 'Date Added',"
                    + "status as 'Status' from budget_officer_and_position";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            testingan.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    
    
    
    
   
    
    private void Budget_Officer_Information() {
        try {
            String sql = "select id as 'ID', Fullname as 'Fullname', Position as 'Position', date_added as 'Date Added',"
                    + "status as 'Status' from budget_officer_and_position";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            webTable1_bud_ofcr_inf.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    //Method para Logs kung nag Update og User(s) ang admin
    private void Update_User_Account_Logs() {
        try {
            String SQL = "Insert into logs (Personel_Users, Activity, Date) values (?,?,now())";
            pst = (PreparedStatement) conn.prepareStatement(SQL);
            pst.setString(1, jMenu3_admin.getText());
            //pst.setString(1, rs.getString("Privileges") + " [] [] Username: " + rs.getString("Username"));
            //pst.setString(1, "Username: " + this.rs.getString("Username"));
            pst.setString(2, "Updating Account of " + webTextField1_name.getText());
            pst.execute();

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//end of method Update_Account_Logs

    private void Update_Officer_Account_Logs() {
        try {
            String SQL = "Insert into logs(Personel_Users, Activity, Date) values (?,?,now())";
            pst = (PreparedStatement) conn.prepareStatement(SQL);
            pst.setString(1, jMenu3_admin.getText());
            //pst.setString(1, rs.getString("Privileges") + " [] [] Username: " + rs.getString("Username"));
            //pst.setString(1, "Username: " + this.rs.getString("Username"));
            pst.setString(2, "Updating Officer " + webTextField1_officer_fullname.getText());
            pst.execute();

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    private void Update_Budget_Officer_Account_Logs() {
        try {
            String SQL = "Insert into logs (Personel_Users, Activity, Date) values (?,?,now())";
            pst = (PreparedStatement) conn.prepareStatement(SQL);
            pst.setString(1, jMenu3_admin.getText());
            //pst.setString(1, rs.getString("Privileges") + " [] [] Username: " + rs.getString("Username"));
            //pst.setString(1, "Username: " + this.rs.getString("Username"));
            pst.setString(2, "Updating Budget Officer " + webTextField1_bdgt_ofcr_fname.getText());
            pst.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    private void Logout() {
        try {
            String SQL = "Insert into logs (Personel_Users, Activity, Date) values (?,?,now())";
            pst = (PreparedStatement) conn.prepareStatement(SQL);
            pst.setString(1, jMenu3_admin.getText());
            //pst.setString(1, rs.getString("Privileges") + " [] [] Username: " + rs.getString("Username"));
            //pst.setString(1, "Username: " + this.rs.getString("Username"));
            pst.setString(2, "Logout");
            pst.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
}
