
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
//import static java.util.logging.Level.OFF;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
//import static jdk.nashorn.internal.runtime.Debug.id;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jcarrierpigeon.WindowPosition;
import net.sf.jtelegraph.Telegraph;
import net.sf.jtelegraph.TelegraphQueue;
import net.sf.jtelegraph.TelegraphType;
//import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yhel001
 */
public final class BURS_Frame extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    JTextField date = new JTextField();
    JTable table = new JTable();
    JTextField number = new JTextField();
    JTextField user = new JTextField();

    public BURS_Frame() {
        conn = (Connection) JavaMySqlConnection.ConnectDb();
        initComponents();
        String user_name = ORS_BURS_FUNDS_Frame.jMenu1_user.getText();
        user.setText(user_name);
        //jMenu5_user.setText(init);
        jXTable1_burs_view.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jXTable1_burs_view.getTableHeader().setReorderingAllowed(false);
        Table_Pane_BURS();
        BURS_View();
        U_Code();
        Officer();
        Budget_Officer();
        setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webPanel1 = new com.alee.laf.panel.WebPanel();
        webLabel2 = new com.alee.laf.label.WebLabel();
        webLabel3 = new com.alee.laf.label.WebLabel();
        webLabel4 = new com.alee.laf.label.WebLabel();
        webLabel5 = new com.alee.laf.label.WebLabel();
        webLabel6 = new com.alee.laf.label.WebLabel();
        webTextField1_no = new com.alee.laf.text.WebTextField();
        webDateField1_date = new com.alee.extended.date.WebDateField();
        webTextField2_fund = new com.alee.laf.text.WebTextField();
        webTextField3_agency = new com.alee.laf.text.WebTextField();
        webTextField4_payee = new com.alee.laf.text.WebTextField();
        webTextField5_office = new com.alee.laf.text.WebTextField();
        webLabel7 = new com.alee.laf.label.WebLabel();
        webLabel8 = new com.alee.laf.label.WebLabel();
        webLabel9 = new com.alee.laf.label.WebLabel();
        webLabel11 = new com.alee.laf.label.WebLabel();
        webLabel12 = new com.alee.laf.label.WebLabel();
        webTextField7_res_center = new com.alee.laf.text.WebTextField();
        webTextField8_par = new com.alee.laf.text.WebTextField();
        webTextField10_ofcr_pos = new com.alee.laf.text.WebTextField();
        webTextField11_amount = new com.alee.laf.text.WebTextField();
        webLabel14 = new com.alee.laf.label.WebLabel();
        webLabel15 = new com.alee.laf.label.WebLabel();
        webLabel17 = new com.alee.laf.label.WebLabel();
        webLabel18 = new com.alee.laf.label.WebLabel();
        webTextField9_address = new com.alee.laf.text.WebTextField();
        webComboBox2_officer = new com.alee.laf.combobox.WebComboBox();
        webTextField15_budget_ofcr_pos = new com.alee.laf.text.WebTextField();
        webLabel19 = new com.alee.laf.label.WebLabel();
        webLabel1 = new com.alee.laf.label.WebLabel();
        webLabel20 = new com.alee.laf.label.WebLabel();
        webLabel21 = new com.alee.laf.label.WebLabel();
        webComboBox3_uacs = new com.alee.laf.combobox.WebComboBox();
        webTextField17_part_stat = new com.alee.laf.text.WebTextField();
        webLabel16 = new com.alee.laf.label.WebLabel();
        webTextField1_mfo_pap = new com.alee.laf.text.WebTextField();
        webComboBox1_budget_ofcr = new com.alee.laf.combobox.WebComboBox();
        webTextField1_bursno = new com.alee.laf.text.WebTextField();
        webTextField2_jev = new com.alee.laf.text.WebTextField();
        webTextField3_rci = new com.alee.laf.text.WebTextField();
        webLabel10 = new com.alee.laf.label.WebLabel();
        webLabel22 = new com.alee.laf.label.WebLabel();
        webTextField4_utilization = new com.alee.laf.text.WebTextField();
        webTextField5_notyetdue = new com.alee.laf.text.WebTextField();
        webLabel23 = new com.alee.laf.label.WebLabel();
        webLabel24 = new com.alee.laf.label.WebLabel();
        webLabel25 = new com.alee.laf.label.WebLabel();
        webLabel26 = new com.alee.laf.label.WebLabel();
        webTextField1_dad = new com.alee.laf.text.WebTextField();
        webLabel13 = new com.alee.laf.label.WebLabel();
        webTextField1_payment = new com.alee.laf.text.WebTextField();
        webTextField16 = new com.alee.laf.text.WebTextField();
        webButton2_print = new com.alee.laf.button.WebButton();
        webButton1_save_trans = new com.alee.laf.button.WebButton();
        webButton1 = new com.alee.laf.button.WebButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1_burs_view = new org.jdesktop.swingx.JXTable();
        jXBusyLabel1_status = new org.jdesktop.swingx.JXBusyLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setTitle("BURS Transaction");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        webLabel2.setText("Date:");

        webLabel3.setText("Fund:");

        webLabel4.setText("Agency:");

        webLabel5.setText("Payee:");

        webLabel6.setText("Office:");

        webTextField1_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                webTextField1_noKeyTyped(evt);
            }
        });

        webLabel7.setText("Address:");

        webLabel8.setText("Responsibility Center:");

        webLabel9.setText("Particulars:");

        webLabel11.setText("Particulars Status:");

        webLabel12.setText("Amount:");

        webTextField10_ofcr_pos.setEditable(false);

        webLabel14.setText("JEV:");

        webLabel15.setText("RCI:");

        webLabel17.setText("Officer:");

        webLabel18.setText("Position:");

        webComboBox2_officer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Officer" }));
        webComboBox2_officer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webComboBox2_officerActionPerformed(evt);
            }
        });

        webTextField15_budget_ofcr_pos.setEditable(false);

        webLabel19.setText("No:");

        webLabel1.setText("UACS Code:");

        webLabel20.setText("Budget Officer:");

        webLabel21.setText("Position:");

        webComboBox3_uacs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UACS CODE" }));
        webComboBox3_uacs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webComboBox3_uacsActionPerformed(evt);
            }
        });

        webLabel16.setText("MFO/PAP:");

        webTextField1_mfo_pap.setEditable(false);

        webComboBox1_budget_ofcr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Budget Officer" }));
        webComboBox1_budget_ofcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webComboBox1_budget_ofcrActionPerformed(evt);
            }
        });

        webLabel10.setText("Utilization:");

        webLabel22.setText("Not Yet Due:");

        webLabel23.setText("BURS No.:");

        webLabel24.setText("Due");

        webLabel25.setText("and");

        webLabel26.setText("Demandable:");

        webLabel13.setText("Payment:");

        javax.swing.GroupLayout webPanel1Layout = new javax.swing.GroupLayout(webPanel1);
        webPanel1.setLayout(webPanel1Layout);
        webPanel1Layout.setHorizontalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2_mess, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webTextField5_office, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField4_payee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField3_agency, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField2_fund, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webDateField1_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField1_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webTextField11_amount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webComboBox3_uacs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField1_mfo_pap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField8_par, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField7_res_center, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField9_address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webTextField1_bursno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField17_part_stat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField15_budget_ofcr_pos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webComboBox1_budget_ofcr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField10_ofcr_pos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webComboBox2_officer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, webPanel1Layout.createSequentialGroup()
                        .addComponent(webLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(webLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(webLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webTextField1_dad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webTextField5_notyetdue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(webTextField1_payment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(webTextField4_utilization, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(webTextField3_rci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(webTextField2_jev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(203, 203, 203))
        );
        webPanel1Layout.setVerticalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(webLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(webLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(webLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(webLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(webLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(webTextField1_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(webDateField1_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(webTextField2_fund, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(webTextField3_agency, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(webTextField4_payee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(webTextField5_office, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(webLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(webLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(webLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(webLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(webTextField9_address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(webTextField7_res_center, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(webTextField8_par, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(webTextField1_mfo_pap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(webComboBox3_uacs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(webTextField11_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(webPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(webPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(webLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(webTextField2_jev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(webPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(webLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(webTextField3_rci, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(webPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(webLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(webTextField4_utilization, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(webPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(webLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(webLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(webLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(webTextField1_dad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(webPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(webLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(webLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17)
                            .addComponent(webLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(webLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(webLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(webLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(webTextField1_bursno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(webPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(webLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(webTextField5_notyetdue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(webPanel1Layout.createSequentialGroup()
                                .addComponent(webComboBox2_officer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(webTextField10_ofcr_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(webComboBox1_budget_ofcr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(webTextField15_budget_ofcr_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(webLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(webTextField1_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(webTextField17_part_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jLabel2_mess, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        webPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {webTextField1_payment, webTextField4_utilization});

        getContentPane().add(webPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1160, 220));

        webTextField16.setInputPrompt("Search UACS CODE here...");
        webTextField16.setInputPromptFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
        getContentPane().add(webTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 390, 30));

        webButton2_print.setText("PRINT THIS REPORT");
        webButton2_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webButton2_printMouseClicked(evt);
            }
        });
        webButton2_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton2_printActionPerformed(evt);
            }
        });
        getContentPane().add(webButton2_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 150, 40));

        webButton1_save_trans.setText("SAVE TRANSACTION");
        webButton1_save_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1_save_transActionPerformed(evt);
            }
        });
        getContentPane().add(webButton1_save_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 150, 40));

        webButton1.setText("UPDATE TRANSACTION");
        getContentPane().add(webButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 150, 40));

        jXTable1_burs_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jXTable1_burs_view.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jXTable1_burs_view.setColumnMargin(5);
        jXTable1_burs_view.setFillsViewportHeight(false);
        jXTable1_burs_view.setRowHeight(25);
        jXTable1_burs_view.setRowMargin(5);
        jXTable1_burs_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTable1_burs_viewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jXTable1_burs_view);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 1160, 230));

        jXBusyLabel1_status.setText("Printing in progress. . .");
        getContentPane().add(jXBusyLabel1_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 600, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/BURS_Bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 650));

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);
        jMenuBar2.add(jMenu5_user);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(1186, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void webComboBox3_uacsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webComboBox3_uacsActionPerformed
        String sql = "Select * from acct_titles_and_codes where u_code = ?";
        try {
            pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, webComboBox3_uacs.getSelectedItem().toString());
            rs = pst.executeQuery();
            if (rs.next()) {
                webTextField1_mfo_pap.setText(this.rs.getString("acct_title"));
                webTextField1_mfo_pap.setToolTipText(webTextField1_mfo_pap.getText());
            } else {
                System.err.print("ERROR");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_webComboBox3_uacsActionPerformed

    private void webButton1_save_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1_save_transActionPerformed
        String SQL_Insert = "Insert into burs_transaction (no,date,fund,agency,payee,office,address,respons_center,particulars,mfo_pap,uacs_code,"
                + "amount,officer,ofcr_position,budget_ofcr,budget_ofcr_position,particular_stat,burs_no,jev,rci,utilization,payment,not_yet_due,due_and_dem)"
                + " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try {
            pst = (PreparedStatement) conn.prepareStatement(SQL_Insert);
            SimpleDateFormat formatted = new SimpleDateFormat("yyyy-MM-dd");
            String trans_date = formatted.format(webDateField1_date.getDate());
            date.setText(trans_date);
            pst.setString(1, webTextField1_no.getText());
            pst.setString(2, date.getText());
            pst.setString(3, webTextField2_fund.getText());
            pst.setString(4, webTextField3_agency.getText());
            pst.setString(5, webTextField4_payee.getText());
            pst.setString(6, webTextField5_office.getText());
            pst.setString(7, webTextField9_address.getText());
            pst.setString(8, webTextField7_res_center.getText());
            pst.setString(9, webTextField8_par.getText());
            pst.setString(10, webTextField1_mfo_pap.getText());
            pst.setString(11, webComboBox3_uacs.getSelectedItem().toString());
            pst.setString(12, webTextField11_amount.getText());
            pst.setString(13, webComboBox2_officer.getSelectedItem().toString());
            pst.setString(14, webTextField10_ofcr_pos.getText());
            pst.setString(15, webComboBox1_budget_ofcr.getSelectedItem().toString());
            pst.setString(16, webTextField15_budget_ofcr_pos.getText());
            pst.setString(17, webTextField17_part_stat.getText());
            pst.setString(18, webTextField1_bursno.getText());
            pst.setString(19, webTextField2_jev.getText());
            pst.setString(20, webTextField3_rci.getText());
            pst.setString(21, webTextField4_utilization.getText());
            pst.setString(22, webTextField1_payment.getText());
            pst.setString(23, webTextField5_notyetdue.getText());
            pst.setString(24, webTextField1_dad.getText());
            pst.execute();
            Telegraph tel = new Telegraph("Message", "<html>"
                    + "<body style='color:green;font-size:13px'>"
                    + "<b> BURS Transaction Successfull Saved..."
                    + "</b>"
                    + "</body>"
                    + "</html>", TelegraphType.DOCUMENT_ADD, WindowPosition.TOPRIGHT, 2000);
            TelegraphQueue TQ = new TelegraphQueue();
            TQ.add(tel);
            Table_Pane_BURS();
            BURS_View();
            //dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_webButton1_save_transActionPerformed

    private void webComboBox2_officerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webComboBox2_officerActionPerformed
        String SQL_Find_Officer = "Select * from officers_and_position where Fullname = ?";
        try {
            pst = (PreparedStatement) conn.prepareStatement(SQL_Find_Officer);
            pst.setString(1, webComboBox2_officer.getSelectedItem().toString());
            rs = pst.executeQuery();
            if (rs.next()) {
                webTextField10_ofcr_pos.setText(this.rs.getString("position"));
                //webTextField10_ofcr_pos.setToolTipText(webTextField10_ofcr_pos.getText());
            } else {
                System.err.print("ERROR");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_webComboBox2_officerActionPerformed

    private void webComboBox1_budget_ofcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webComboBox1_budget_ofcrActionPerformed
        String SQL_Find_Budget_Officer = "Select * from budget_officer_and_position where Fullname = ?";
        try {
            pst = (PreparedStatement) conn.prepareStatement(SQL_Find_Budget_Officer);
            pst.setString(1, webComboBox1_budget_ofcr.getSelectedItem().toString());
            rs = pst.executeQuery();
            if (rs.next()) {
                webTextField15_budget_ofcr_pos.setText(this.rs.getString("Position"));
                //webTextField15_budget_ofcr_pos.setToolTipText(webTextField15_budget_ofcr_pos.getText());
            } else {
                System.err.print("ERROR");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_webComboBox1_budget_ofcrActionPerformed

    private void jXTable1_burs_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable1_burs_viewMouseClicked
        int row = jXTable1_burs_view.getSelectedRow();
        String Table_Clickno = (jXTable1_burs_view.getModel().getValueAt(row, 0).toString());
        number.setText(Table_Clickno);
    }//GEN-LAST:event_jXTable1_burs_viewMouseClicked

    private void webButton2_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton2_printActionPerformed
        //jXBusyLabel1_status.setBusy(true);
        Print_Logs();
        try {
            JasperDesign jasperDesign = JRXmlLoader.load("Burs_transaction.jrxml");
            String sql = "select * from burs_transaction where no = '" + number.getText() + "'";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jasperDesign.setQuery(newQuery);

            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);
            JasperViewer jview = new JasperViewer(jasperPrint, false, null);
            jview.setTitle("Report Viewer");
            //jview.setIconImage(new javax.swing.ImageIcon(getClass().getResource("tatelogo.png")).getImage());
            //jview.setSize(800, 600);
            //jview.setVisible(true);
            JasperViewer.viewReport(jasperPrint, false);
            BURS_Frame bf = new BURS_Frame();
            bf.getContentPane().add(new JRViewer(jasperPrint));
            bf.pack();
            bf.setVisible(true);
        } catch (Exception ex) {

            //JOptionPane.showMessageDialog(null, e);
            //e.printStackTrace();
        }
    }//GEN-LAST:event_webButton2_printActionPerformed

    private void webTextField1_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_webTextField1_noKeyTyped
        webTextField1_bursno.setText(webTextField1_no.getText());
    }//GEN-LAST:event_webTextField1_noKeyTyped

    private void webButton2_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webButton2_printMouseClicked
        //jXBusyLabel1_status.setBusy(true);
    }//GEN-LAST:event_webButton2_printMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ORS_Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ORS_Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ORS_Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ORS_Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BURS_Frame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static final javax.swing.JLabel jLabel2_mess = new javax.swing.JLabel();
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    public static final javax.swing.JMenu jMenu5_user = new javax.swing.JMenu();
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel1_status;
    private org.jdesktop.swingx.JXTable jXTable1_burs_view;
    private com.alee.laf.button.WebButton webButton1;
    private com.alee.laf.button.WebButton webButton1_save_trans;
    private com.alee.laf.button.WebButton webButton2_print;
    private com.alee.laf.combobox.WebComboBox webComboBox1_budget_ofcr;
    private com.alee.laf.combobox.WebComboBox webComboBox2_officer;
    private com.alee.laf.combobox.WebComboBox webComboBox3_uacs;
    private com.alee.extended.date.WebDateField webDateField1_date;
    private com.alee.laf.label.WebLabel webLabel1;
    private com.alee.laf.label.WebLabel webLabel10;
    private com.alee.laf.label.WebLabel webLabel11;
    private com.alee.laf.label.WebLabel webLabel12;
    private com.alee.laf.label.WebLabel webLabel13;
    private com.alee.laf.label.WebLabel webLabel14;
    private com.alee.laf.label.WebLabel webLabel15;
    private com.alee.laf.label.WebLabel webLabel16;
    private com.alee.laf.label.WebLabel webLabel17;
    private com.alee.laf.label.WebLabel webLabel18;
    private com.alee.laf.label.WebLabel webLabel19;
    private com.alee.laf.label.WebLabel webLabel2;
    private com.alee.laf.label.WebLabel webLabel20;
    private com.alee.laf.label.WebLabel webLabel21;
    private com.alee.laf.label.WebLabel webLabel22;
    private com.alee.laf.label.WebLabel webLabel23;
    private com.alee.laf.label.WebLabel webLabel24;
    private com.alee.laf.label.WebLabel webLabel25;
    private com.alee.laf.label.WebLabel webLabel26;
    private com.alee.laf.label.WebLabel webLabel3;
    private com.alee.laf.label.WebLabel webLabel4;
    private com.alee.laf.label.WebLabel webLabel5;
    private com.alee.laf.label.WebLabel webLabel6;
    private com.alee.laf.label.WebLabel webLabel7;
    private com.alee.laf.label.WebLabel webLabel8;
    private com.alee.laf.label.WebLabel webLabel9;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.text.WebTextField webTextField10_ofcr_pos;
    private com.alee.laf.text.WebTextField webTextField11_amount;
    private com.alee.laf.text.WebTextField webTextField15_budget_ofcr_pos;
    private com.alee.laf.text.WebTextField webTextField16;
    private com.alee.laf.text.WebTextField webTextField17_part_stat;
    private com.alee.laf.text.WebTextField webTextField1_bursno;
    private com.alee.laf.text.WebTextField webTextField1_dad;
    private com.alee.laf.text.WebTextField webTextField1_mfo_pap;
    public static com.alee.laf.text.WebTextField webTextField1_no;
    private com.alee.laf.text.WebTextField webTextField1_payment;
    private com.alee.laf.text.WebTextField webTextField2_fund;
    private com.alee.laf.text.WebTextField webTextField2_jev;
    private com.alee.laf.text.WebTextField webTextField3_agency;
    private com.alee.laf.text.WebTextField webTextField3_rci;
    private com.alee.laf.text.WebTextField webTextField4_payee;
    private com.alee.laf.text.WebTextField webTextField4_utilization;
    private com.alee.laf.text.WebTextField webTextField5_notyetdue;
    private com.alee.laf.text.WebTextField webTextField5_office;
    private com.alee.laf.text.WebTextField webTextField7_res_center;
    private com.alee.laf.text.WebTextField webTextField8_par;
    private com.alee.laf.text.WebTextField webTextField9_address;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/tatelogo.png")));
    }

    public void U_Code() {
        String SQL_Combo_U_Code = "Select * from acct_titles_and_codes";
        try {
            pst = (PreparedStatement) conn.prepareStatement(SQL_Combo_U_Code);
//            pst.setString(1, webComboBox3_uacs.getSelectedItem().toString());
            rs = pst.executeQuery();
            while (rs.next()) {
                // webTextField1_mfo_pap.setText(this.rs.getString("u_code"));
                // webComboBox3_uacs.setModel(new javax.swing.DefaultComboBoxModel(new String[]{ this.rs.getString("u_code")}));
                webComboBox3_uacs.addItem(this.rs.getString("u_code"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Officer() {
        String SQL_Combo_Officer_ = "Select * from officers_and_position";
        try {
            pst = (PreparedStatement) conn.prepareStatement(SQL_Combo_Officer_);
//            pst.setString(1, webComboBox3_uacs.getSelectedItem().toString());
            rs = pst.executeQuery();
            while (rs.next()) {
                // webTextField1_mfo_pap.setText(this.rs.getString("u_code"));
                // webComboBox3_uacs.setModel(new javax.swing.DefaultComboBoxModel(new String[]{ this.rs.getString("u_code")}));
                webComboBox2_officer.addItem(this.rs.getString("Fullname"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Budget_Officer() {
        String SQL_Combo_Officer_ = "Select * from budget_officer_and_position";
        try {
            pst = (PreparedStatement) conn.prepareStatement(SQL_Combo_Officer_);
//            pst.setString(1, webComboBox3_uacs.getSelectedItem().toString());
            rs = pst.executeQuery();
            while (rs.next()) {
                // webTextField1_mfo_pap.setText(this.rs.getString("u_code"));
                // webComboBox3_uacs.setModel(new javax.swing.DefaultComboBoxModel(new String[]{ this.rs.getString("u_code")}));
                webComboBox1_budget_ofcr.addItem(this.rs.getString("Fullname"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Table_Pane_BURS() {

        for (int i = 0; i < jXTable1_burs_view.getColumnCount(); i++) {
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) jXTable1_burs_view.getColumnModel();
            TableColumn col = colModel.getColumn(i);
            int width = 500;

            TableCellRenderer renderer = col.getHeaderRenderer();
            for (int r = 0; r < jXTable1_burs_view.getRowCount(); r++) {
                renderer = jXTable1_burs_view.getCellRenderer(r, i);
                Component comp = renderer.getTableCellRendererComponent(jXTable1_burs_view, jXTable1_burs_view.getValueAt(r, i),
                        false, false, r, i);
                width = Math.max(width, comp.getPreferredSize().width);
            }

            col.setPreferredWidth(width + 400);
            col.setMaxWidth(width);
            col.setWidth(width);
        }
    }
    //no,date,fund,agency,payee,office,address,respons_center,particulars,mfo_pap,uacs_code,"
    //   + "amount,officer,ofcr_position,budget_ofcr,budget_ofcr_position,particular_stat,ors_no,
    //jev,rci,obligation,payment,not_yet_due,due_and_dem

    private void BURS_View() {
        String SQL_Ors_View = "Select no as 'No',date as 'Date',fund as 'Fund',agency as 'Agency',payee as 'Payee',"
                + "office as 'Office', address as 'Address', respons_center as 'Responsibility Center', particulars as 'Particulars',"
                + "mfo_pap as 'MFO/PAP',uacs_code as 'UACS Code',amount as 'Amount',officer as 'Officer',"
                + "ofcr_position as 'Officer Position',budget_ofcr as 'Budget Officer',budget_ofcr_position as 'Budget Officer Position',"
                + "particular_stat as 'Particular Status',burs_no as 'BURS No',jev as 'JEV No', rci as 'RCI No',utilization as 'Utilization',"
                + "payment as 'Payment',not_yet_due as 'Not Yet Due',due_and_dem as 'Due and Demandable' from burs_transaction";
        try {
            //String sql = "select id as 'User ID', Personel_Users as 'Users', Activity as 'Activity', Date as 'Date and time of Activity' from log_activities order by id desc";
            pst = (PreparedStatement) conn.prepareStatement(SQL_Ors_View);
            rs = pst.executeQuery();
            jXTable1_burs_view.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            e.printStackTrace();

        }

    }

    public void Print_Logs() {
        String SQL_print_logs = "Insert into logs(Personel_Users, Activity, Date) values (?,?,now())";
        try {
            pst = (PreparedStatement) conn.prepareStatement(SQL_print_logs);
            pst.setString(1, user.getText());
            pst.setString(2, "Print Burs Transaction");
            pst.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
