
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jcarrierpigeon.WindowPosition;
import net.sf.jtelegraph.Telegraph;
import net.sf.jtelegraph.TelegraphQueue;
import net.sf.jtelegraph.TelegraphType;
import org.jdesktop.swingx.JXBusyLabel;
import org.jdesktop.swingx.JXDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yhel001
 */
public final class Master_Key_Frame extends javax.swing.JFrame {

    private final int time = 1;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public Master_Key_Frame() {
        conn = (Connection) JavaMySqlConnection.ConnectDb();
        initComponents();
        //jXBusyLabel1.setBusy(true);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webStepLabel1 = new com.alee.extended.label.WebStepLabel();
        webPasswordField1_password = new com.alee.laf.text.WebPasswordField();
        webButton1_login = new com.alee.laf.button.WebButton();
        webButton2_cancel = new com.alee.laf.button.WebButton();
        webCheckBox1 = new com.alee.laf.checkbox.WebCheckBox();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        jXBusyLabel1 = new org.jdesktop.swingx.JXBusyLabel();
        webProgressBar1 = new com.alee.laf.progressbar.WebProgressBar();
        jLabel1 = new javax.swing.JLabel();

        webStepLabel1.setText("webStepLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Key  Field");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        webPasswordField1_password.setInputPrompt("Input Master Key to Register");
        webPasswordField1_password.setInputPromptFont(new java.awt.Font("Yu Gothic UI", 3, 12)); // NOI18N
        webPasswordField1_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webPasswordField1_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(webPasswordField1_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 36));

        webButton1_login.setText("GO ->");
        webButton1_login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webButton1_login.setMaximumSize(new java.awt.Dimension(50, 25));
        webButton1_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1_loginActionPerformed(evt);
            }
        });
        webButton1_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                webButton1_loginKeyPressed(evt);
            }
        });
        getContentPane().add(webButton1_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 33));

        webButton2_cancel.setText("CANCEL");
        webButton2_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        webButton2_cancel.setMinimumSize(new java.awt.Dimension(50, 25));
        webButton2_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton2_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(webButton2_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 70, 33));

        webCheckBox1.setText("Show Password");
        webCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(webCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 195, -1));

        jXHyperlink1.setText("Change Password here");
        jXHyperlink1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jXHyperlink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink1ActionPerformed(evt);
            }
        });
        getContentPane().add(jXHyperlink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));
        getContentPane().add(jXBusyLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        webProgressBar1.setMaximum(10);
        getContentPane().add(webProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Admin_Login_BG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 320, 220));

        setSize(new java.awt.Dimension(308, 222));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void webButton2_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton2_cancelActionPerformed
        System_Admin_and_User_Login saaul = new System_Admin_and_User_Login();
        saaul.setVisible(true);
        dispose();
        saaul.dispose();
    }//GEN-LAST:event_webButton2_cancelActionPerformed

    private void webButton1_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1_loginActionPerformed
        /*     
         if (webTextField1_username.getText().isEmpty() || webPasswordField1_password.getText().isEmpty()) {
         jXBusyLabel1_status.setBusy(true);
         //jXBusyLabel1_status.isBusy();
         Telegraph tele = new Telegraph("Message", "<html><body style='color:red;font-size:13px'><b>"
         + "Please provide some text..</b></body></html>", TelegraphType.APPLICATION_WARNING, WindowPosition.TOPRIGHT, 1200);
         TelegraphQueue q = new TelegraphQueue();
         q.add(tele);
         //jXBusyLabel1_status.setBusy(false);

         } else {
            
         Telegraph tele = new Telegraph("Message", "<html><body style='color:red;font-size:13px'><b>"
         + "You have Successfully Login...</b></body></html>", TelegraphType.NOTIFICATION_INFO, WindowPosition.TOPRIGHT, 1200);
         TelegraphQueue q = new TelegraphQueue();
         q.add(tele);
            
         }
    
         // JOptionPane.showMessageDialog(null, "<html><body style='color:red;font-size:13px'><b>You have Successfully Login!!</b></body></html>");
         */
        //String user = webTextField1_username.getText();
        //jXBusyLabel1.setBusy(true);

        //t.setDaemon(isActive());
        String pass = webPasswordField1_password.getText();
        //String d="Welcome"+"  "+c+"\n"+"Get Started!!!";
        String str = "select * from admin where master_key = ?";
        try {
            pst = (PreparedStatement) conn.prepareStatement(str);
            //    pst.setString(1, webTextField1_username.getText());
            pst.setString(1, webPasswordField1_password.getText());
            rs = pst.executeQuery();

            //t.stop();
            if (rs.next()) {
                // JOptionPane.showMessageDialog(null, "You're Succesfully Login!");
              /*  jXBusyLabel1_status.setBusy(true);
                 jXBusyLabel1_status.getDelay();*/
                /* for (int i = 0; i <= time; i++) {
                 jXBusyLabel1_status.setBusy(true);
                 new Thread() {
                 public void run() {
                 Budget_Main_Panel b = new Budget_Main_Panel();
                 b.setVisible(true);
                 }
                 }.start();
                 }*/
                Registration r = new Registration();
                r.setVisible(true);
                /* Telegraph tele = new Telegraph("Message", "<html><body style='color:red;font-size:13px'><b>"
                 + "You have Successfully Login...</b></body></html>", TelegraphType.NOTIFICATION_INFO, WindowPosition.TOPRIGHT, 1200);
                 TelegraphQueue q = new TelegraphQueue();
                 q.add(tele);*/
                dispose();
            } else if (pass.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please Input Value. . .", "Warning", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Master Key Mismatch. . .", "Warning", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException ex) {
            ex.getErrorCode();
        }
    }//GEN-LAST:event_webButton1_loginActionPerformed

    private void webPasswordField1_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webPasswordField1_passwordActionPerformed
        webButton1_login.doClick();
    }//GEN-LAST:event_webPasswordField1_passwordActionPerformed

    private void webCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webCheckBox1ActionPerformed
        if (webCheckBox1.isSelected()) {
            webPasswordField1_password.setEchoChar((char) 0);
        } else {
            webPasswordField1_password.setEchoChar('*');
        }
    }//GEN-LAST:event_webCheckBox1ActionPerformed

    private void jXHyperlink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink1ActionPerformed
        Master_Key_Frame1_Update mkfu = new Master_Key_Frame1_Update();
        mkfu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jXHyperlink1ActionPerformed

    private void webButton1_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_webButton1_loginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_webButton1_loginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_Key_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_Key_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_Key_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_Key_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_Key_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private com.alee.laf.button.WebButton webButton1_login;
    private com.alee.laf.button.WebButton webButton2_cancel;
    private com.alee.laf.checkbox.WebCheckBox webCheckBox1;
    private com.alee.laf.text.WebPasswordField webPasswordField1_password;
    private com.alee.laf.progressbar.WebProgressBar webProgressBar1;
    private com.alee.extended.label.WebStepLabel webStepLabel1;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/tatelogo.png")));
    }

}
