
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.sf.jcarrierpigeon.WindowPosition;
import net.sf.jtelegraph.Telegraph;
import net.sf.jtelegraph.TelegraphQueue;
import net.sf.jtelegraph.TelegraphType;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ariel Yhel Endino
 */
public class ORS_BURS_FUNDS_Frame extends javax.swing.JFrame {

    /**
     * Creates new form ORS_BURS_FUNDS_Frame
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public ORS_BURS_FUNDS_Frame() {
        conn = (Connection) JavaMySqlConnection.ConnectDb();
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jXHyperlink2_burs = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink1_ors = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink1_funds = new org.jdesktop.swingx.JXHyperlink();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1__sett = new javax.swing.JMenu();
        jMenuItem1_allotment = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Wala sah");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jXHyperlink2_burs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Burs.png"))); // NOI18N
        jXHyperlink2_burs.setText("");
        jXHyperlink2_burs.setContentAreaFilled(false);
        jXHyperlink2_burs.setFocusPainted(false);
        jXHyperlink2_burs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXHyperlink2_bursMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jXHyperlink2_bursMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jXHyperlink2_bursMouseExited(evt);
            }
        });
        getContentPane().add(jXHyperlink2_burs, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 130, 120));

        jXHyperlink1_ors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Ors.png"))); // NOI18N
        jXHyperlink1_ors.setText("");
        jXHyperlink1_ors.setContentAreaFilled(false);
        jXHyperlink1_ors.setFocusPainted(false);
        jXHyperlink1_ors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXHyperlink1_orsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jXHyperlink1_orsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jXHyperlink1_orsMouseExited(evt);
            }
        });
        getContentPane().add(jXHyperlink1_ors, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 130, 120));

        jXHyperlink1_funds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Funds.png"))); // NOI18N
        jXHyperlink1_funds.setText("");
        jXHyperlink1_funds.setContentAreaFilled(false);
        jXHyperlink1_funds.setFocusPainted(false);
        jXHyperlink1_funds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jXHyperlink1_fundsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jXHyperlink1_fundsMouseExited(evt);
            }
        });
        getContentPane().add(jXHyperlink1_funds, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 130, 120));
        getContentPane().add(jLabel4_greetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 280, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/ORS_BURS_FUNDS_BG.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 230));

        jMenu1__sett.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Settings_Icon.png"))); // NOI18N

        jMenuItem1_allotment.setText("Add Allotment");
        jMenuItem1_allotment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1_allotmentMousePressed(evt);
            }
        });
        jMenu1__sett.add(jMenuItem1_allotment);

        jMenuItem2.setText("View Logs");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1__sett.add(jMenuItem2);

        jMenuItem3.setText("Logout");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenu1__sett.add(jMenuItem3);

        jMenuBar1.add(jMenu1__sett);

        jMenu1_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User.png"))); // NOI18N
        jMenu1_user.setEnabled(false);
        jMenu1_user.setFocusPainted(true);
        jMenu1_user.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu1_user.setInheritsPopupMenu(true);
        jMenuBar1.add(jMenu1_user);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(578, 248));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jXHyperlink2_bursMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXHyperlink2_bursMouseEntered
        //jXHyperlink2_burs.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/Burs_Shadow.png")));
    }//GEN-LAST:event_jXHyperlink2_bursMouseEntered

    private void jXHyperlink2_bursMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXHyperlink2_bursMouseExited
        jXHyperlink2_burs.setIcon(new javax.swing.ImageIcon(getClass().getResource("Backgrounds/Burs.png")));
    }//GEN-LAST:event_jXHyperlink2_bursMouseExited

    private void jXHyperlink1_orsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXHyperlink1_orsMouseEntered
        //jXHyperlink1_ors.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/Ors_Shadow.png")));
    }//GEN-LAST:event_jXHyperlink1_orsMouseEntered

    private void jXHyperlink1_orsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXHyperlink1_orsMouseExited
        jXHyperlink1_ors.setIcon(new javax.swing.ImageIcon(getClass().getResource("Backgrounds/Ors.png")));
    }//GEN-LAST:event_jXHyperlink1_orsMouseExited

    private void jXHyperlink1_fundsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXHyperlink1_fundsMouseEntered
        //jXHyperlink1_funds.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/Fund_Shadow.png")));
    }//GEN-LAST:event_jXHyperlink1_fundsMouseEntered

    private void jXHyperlink1_fundsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXHyperlink1_fundsMouseExited
        jXHyperlink1_funds.setIcon(new javax.swing.ImageIcon(getClass().getResource("Backgrounds/Funds.png")));
    }//GEN-LAST:event_jXHyperlink1_fundsMouseExited

    private void jXHyperlink1_orsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXHyperlink1_orsMouseClicked
        ORS_Frame of = new ORS_Frame();
        of.setVisible(true);
        //hide();
    }//GEN-LAST:event_jXHyperlink1_orsMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        User_Logs ul = new User_Logs();
        ul.setVisible(true);
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        Telegraph tel = new Telegraph("Message", "<html>"
                + "<body style='color:green;font-size:13px'>"
                + "<b> Thank you for using Automated Budget Slip and Funds Monitoring System :)"
                + "</b>"
                + "</body>"
                + "</html>", TelegraphType.NOTIFICATION_DONE, WindowPosition.TOPRIGHT, 1500);
        TelegraphQueue TQ = new TelegraphQueue();
        TQ.add(tel);
        Logout();
        System_Admin_and_User_Login saaul = new System_Admin_and_User_Login();
        saaul.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void jXHyperlink2_bursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXHyperlink2_bursMouseClicked
        BURS_Frame bf = new BURS_Frame();
        bf.setVisible(true);
    }//GEN-LAST:event_jXHyperlink2_bursMouseClicked

    private void jMenuItem1_allotmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1_allotmentMousePressed
        SAOB_Frame sf = new SAOB_Frame();
        sf.setVisible(true);
    }//GEN-LAST:event_jMenuItem1_allotmentMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ORS_BURS_FUNDS_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ORS_BURS_FUNDS_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ORS_BURS_FUNDS_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ORS_BURS_FUNDS_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ORS_BURS_FUNDS_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static final javax.swing.JLabel jLabel4_greetings = new javax.swing.JLabel();
    private javax.swing.JMenu jMenu1__sett;
    public static final javax.swing.JMenu jMenu1_user = new javax.swing.JMenu();
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_allotment;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1_funds;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1_ors;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink2_burs;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/tatelogo.png")));
    }

    private void Logout() {
        String sqli = "Select * from users_table";
        try {
            pst = (PreparedStatement) conn.prepareStatement(sqli);
            rs = pst.executeQuery();
            if (rs.next()) {
                String SQL = "Insert into logs(Personel_Users, Activity, Date) values (?,?,now())";
                pst = (PreparedStatement) conn.prepareStatement(SQL);
                pst.setString(1, jMenu1_user.getText());
                //pst.setString(1, rs.getString("Privileges") + " [] [] Username: " + rs.getString("Username"));
                //pst.setString(1, "Username: " + this.rs.getString("Username"));
                pst.setString(2, "Logout");
                pst.execute();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
}
