
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.sf.jcarrierpigeon.WindowPosition;
import net.sf.jtelegraph.Telegraph;
import net.sf.jtelegraph.TelegraphQueue;
import net.sf.jtelegraph.TelegraphType;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yhel001
 */
public class Registration extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public Registration() {
        conn = JavaMySqlConnection.ConnectDb();
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webTextField1_reg_fname = new com.alee.laf.text.WebTextField();
        webTextField2_reg_minit = new com.alee.laf.text.WebTextField();
        webTextField3_reg_lname = new com.alee.laf.text.WebTextField();
        webTextField4_reg_user = new com.alee.laf.text.WebTextField();
        webComboBox1_reg_priv = new com.alee.laf.combobox.WebComboBox();
        webButton1_submit = new com.alee.laf.button.WebButton();
        webTextField1_reg_position = new com.alee.laf.text.WebTextField();
        webTextField1_reg_pass = new com.alee.laf.text.WebTextField();
        jLabel1_admin_reg = new javax.swing.JLabel();

        setTitle("REGISTRATION");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        webTextField1_reg_fname.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField1_reg_fname.setInputPrompt("Firstname");
        webTextField1_reg_fname.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        getContentPane().add(webTextField1_reg_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 140, 30));

        webTextField2_reg_minit.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField2_reg_minit.setInputPrompt("Middle Initial");
        webTextField2_reg_minit.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        getContentPane().add(webTextField2_reg_minit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 140, 30));

        webTextField3_reg_lname.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField3_reg_lname.setInputPrompt("Lastname");
        webTextField3_reg_lname.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        getContentPane().add(webTextField3_reg_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, 30));

        webTextField4_reg_user.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField4_reg_user.setInputPrompt("Username");
        webTextField4_reg_user.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        webTextField4_reg_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                webTextField4_reg_userKeyReleased(evt);
            }
        });
        getContentPane().add(webTextField4_reg_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 140, 30));

        webComboBox1_reg_priv.setBackground(new java.awt.Color(51, 255, 204));
        webComboBox1_reg_priv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Privileges", "Admin", "Clerk Aide", "Fund Manager" }));
        webComboBox1_reg_priv.setToolTipText("");
        webComboBox1_reg_priv.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webComboBox1_reg_priv.setInheritsPopupMenu(true);
        webComboBox1_reg_priv.setUseFirstValueAsPrototype(true);
        webComboBox1_reg_priv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webComboBox1_reg_privActionPerformed(evt);
            }
        });
        getContentPane().add(webComboBox1_reg_priv, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 30));

        webButton1_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        webButton1_submit.setText("GO ->");
        webButton1_submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        webButton1_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1_submitActionPerformed(evt);
            }
        });
        getContentPane().add(webButton1_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 80, 30));

        webTextField1_reg_position.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField1_reg_position.setInputPrompt("Position");
        webTextField1_reg_position.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        getContentPane().add(webTextField1_reg_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 140, 30));

        webTextField1_reg_pass.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        webTextField1_reg_pass.setInputPrompt("Password");
        webTextField1_reg_pass.setInputPromptFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        webTextField1_reg_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webTextField1_reg_passActionPerformed(evt);
            }
        });
        getContentPane().add(webTextField1_reg_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 140, 30));

        jLabel1_admin_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Registration_BG.png"))); // NOI18N
        getContentPane().add(jLabel1_admin_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 417, -1));

        setSize(new java.awt.Dimension(401, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //int user_validation[] = new int[3];
    private void webButton1_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1_submitActionPerformed
        //  String UsernameCounter;
        String name = webTextField1_reg_fname.getText();
        String minit = webTextField2_reg_minit.getText();
        String lname = webTextField3_reg_lname.getText();
        String position = webTextField1_reg_position.getText();
        String user = webTextField4_reg_user.getText();
        String pass = webTextField1_reg_pass.getText();

        if (name.isEmpty() || minit.isEmpty() || lname.isEmpty() || position.isEmpty() || user.isEmpty() || pass.isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Please fill all the fields...", "Warning", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "<html>"
                    + "<body style='color:red;font-size:10px'>"
                    + "<b>Please fill all the fields..</b>"
                    + "</body>"
                    + "</html>", "System Message", JOptionPane.ERROR_MESSAGE);
        } else if (webComboBox1_reg_priv.getSelectedItem().equals("Privileges")) {
            //JOptionPane.showMessageDialog(null, "Please Choose Privilege for this User", "Warning", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "<html>"
                    + "<body style='color:red;font-size:10px'>"
                    + "<b>Please Choose Privilege for this User.</b>"
                    + "</body>"
                    + "</html>", "System Message", JOptionPane.ERROR_MESSAGE);
        } else if (webTextField4_reg_user.getText().length() == 2 || webTextField4_reg_user.getText().length() == 3
                || webTextField4_reg_user.getText().length() == 4) {
            JOptionPane.showMessageDialog(null, "<html>"
                    + "<body style='color:red;font-size:10px'>"
                    + "<b>Username is atleast 5 characters.</b>"
                    + "</body>"
                    + "</html>", "System Message", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String sql = "Insert into users_table (Firstname,Middle_Initial,Lastname,Privileges,Position,Username,Password,Date_registered) values (?,?,?,?,?,?,?,now())";
                pst = conn.prepareStatement(sql);
                pst.setString(1, webTextField1_reg_fname.getText());
                pst.setString(2, webTextField2_reg_minit.getText());
                pst.setString(3, webTextField3_reg_lname.getText());
                pst.setString(4, webComboBox1_reg_priv.getSelectedItem().toString());
                pst.setString(5, webTextField1_reg_position.getText());
                pst.setString(6, webTextField4_reg_user.getText());
                pst.setString(7, webTextField1_reg_pass.getText());
                pst.execute();
                Telegraph tel = new Telegraph("Message", "<html>"
                        + "<body style='color:green;font-size:13px'>"
                        + "<b> New Account Registered Successfully..."
                        + "</b>"
                        + "</body>"
                        + "</html>", TelegraphType.NOTIFICATION_ADD, WindowPosition.TOPRIGHT, 1500);
                TelegraphQueue TQ = new TelegraphQueue();
                TQ.add(tel);
                dispose();

            } catch (SQLException ex) {
                ex.getErrorCode();
                JOptionPane.showMessageDialog(null, "Username Already Existed...", "", JOptionPane.WARNING_MESSAGE);
                // webTextField1_reg_fname.setText("");
                // webTextField2_reg_minit.setText("");
                // webTextField3_reg_lname.setText("");
                //webComboBox1_reg_priv.setSelectedItem(null);
                // webTextField1_reg_position.setText("");
                webTextField4_reg_user.setText("");
                // webTextField1_reg_pass.setText("");
                // JOptionPane.showMessageDialog(null, "This account has been already registered!!!", "", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_webButton1_submitActionPerformed

    private void webTextField1_reg_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webTextField1_reg_passActionPerformed
        webButton1_submit.doClick();
    }//GEN-LAST:event_webTextField1_reg_passActionPerformed
    // String model[] = {"Admin", "Fund Manager", "Clerk Aide"};
    private void webComboBox1_reg_privActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webComboBox1_reg_privActionPerformed
        /* if (webComboBox1_reg_priv.getSelectedItem().equals("Privileges")||webComboBox1_reg_priv.getSelectedItem().equals("Admin")
         ||webComboBox1_reg_priv.getSelectedItem().equals("Fund Manager")||webComboBox1_reg_priv.getSelectedItem().equals("Clerck Aide")) {
         webComboBox1_reg_priv.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Admin", "Clerk Aide", "Fund Manager"}));
         }*/
    }//GEN-LAST:event_webComboBox1_reg_privActionPerformed

    private void webTextField4_reg_userKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_webTextField4_reg_userKeyReleased
        /*if (webTextField4_reg_user.getText().length() == 3) {
         JOptionPane.showMessageDialog(null, "Username is too short...", "Warning", JOptionPane.ERROR_MESSAGE);
         }*/
    }//GEN-LAST:event_webTextField4_reg_userKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {

            UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");

        } catch (Exception ex) {

        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_admin_reg;
    private com.alee.laf.button.WebButton webButton1_submit;
    private com.alee.laf.combobox.WebComboBox webComboBox1_reg_priv;
    private com.alee.laf.text.WebTextField webTextField1_reg_fname;
    private com.alee.laf.text.WebTextField webTextField1_reg_pass;
    private com.alee.laf.text.WebTextField webTextField1_reg_position;
    private com.alee.laf.text.WebTextField webTextField2_reg_minit;
    private com.alee.laf.text.WebTextField webTextField3_reg_lname;
    private com.alee.laf.text.WebTextField webTextField4_reg_user;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/tatelogo.png")));
    }
}
