
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Component;
import java.sql.ResultSet;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;
import net.sf.jcarrierpigeon.WindowPosition;
import net.sf.jtelegraph.Telegraph;
import net.sf.jtelegraph.TelegraphQueue;
import net.sf.jtelegraph.TelegraphType;
import org.jdesktop.swingx.JXTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ariel Yhel Endino
 */
public final class SAOB_Frame extends javax.swing.JFrame {

    /**
     * Creates new form SAOB_Frame
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    JTextField unobligated = new JXTextField();
    
    public SAOB_Frame() {
        conn = (Connection) JavaMySqlConnection.ConnectDb();
        initComponents();
        webButton3_update.setEnabled(false);
        Table_Pane_Allotments();
        Allotments();
        Agencies();
        AOCE_Title();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webLabel2 = new com.alee.laf.label.WebLabel();
        webLabel3 = new com.alee.laf.label.WebLabel();
        webLabel4 = new com.alee.laf.label.WebLabel();
        webTextField1_dept = new com.alee.laf.text.WebTextField();
        webComboBox1_agency = new com.alee.laf.combobox.WebComboBox();
        webTextField2_fund_code = new com.alee.laf.text.WebTextField();
        webLabel1 = new com.alee.laf.label.WebLabel();
        webLabel5 = new com.alee.laf.label.WebLabel();
        webLabel6 = new com.alee.laf.label.WebLabel();
        webLabel7 = new com.alee.laf.label.WebLabel();
        webTextField5_uacs_code = new com.alee.laf.text.WebTextField();
        webTextField6_allot_rec = new com.alee.laf.text.WebTextField();
        webTextField7_this_rep = new com.alee.laf.text.WebTextField();
        webTextField8_todate = new com.alee.laf.text.WebTextField();
        webLabel9 = new com.alee.laf.label.WebLabel();
        webLabel8 = new com.alee.laf.label.WebLabel();
        webComboBox2_alot_obj_class_exp = new com.alee.laf.combobox.WebComboBox();
        webPanel1 = new com.alee.laf.panel.WebPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        webTable1_allotment_table = new com.alee.laf.table.WebTable();
        webButton1_save = new com.alee.laf.button.WebButton();
        webButton2_cancel = new com.alee.laf.button.WebButton();
        webButton3_update = new com.alee.laf.button.WebButton();
        webLabel10 = new com.alee.laf.label.WebLabel();
        webLabel11 = new com.alee.laf.label.WebLabel();
        webComboBox1_month = new com.alee.laf.combobox.WebComboBox();
        webComboBox2_year = new com.alee.laf.combobox.WebComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        webLabel2.setText("Department:");
        webLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webLabel3.setText("Agency:");
        webLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webLabel4.setText("Fund Code:");
        webLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webTextField1_dept.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        webComboBox1_agency.setEditable(true);
        webComboBox1_agency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose here" }));
        webComboBox1_agency.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        webTextField2_fund_code.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        webLabel1.setText("Allotment / Object Class");
        webLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webLabel5.setText("UACS CODE:");
        webLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webLabel6.setText("Allotment Received:");
        webLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webLabel7.setText("Of Expenditures:");
        webLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webTextField5_uacs_code.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        webTextField6_allot_rec.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        webTextField7_this_rep.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        webTextField8_todate.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        webLabel9.setText("To Date:");
        webLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webLabel8.setText("This Report:");
        webLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webComboBox2_alot_obj_class_exp.setEditable(true);
        webComboBox2_alot_obj_class_exp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose here" }));
        webComboBox2_alot_obj_class_exp.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        webComboBox2_alot_obj_class_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webComboBox2_alot_obj_class_expActionPerformed(evt);
            }
        });

        webPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Allotment Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 12))); // NOI18N

        webTable1_allotment_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        webTable1_allotment_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(webTable1_allotment_table);

        webPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        webButton1_save.setText("SAVE ALLOTMENT");
        webButton1_save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        webButton1_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1_saveActionPerformed(evt);
            }
        });

        webButton2_cancel.setText("CANCEL");
        webButton2_cancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        webButton2_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton2_cancelActionPerformed(evt);
            }
        });

        webButton3_update.setText("UPDATE ALLOTMENT");
        webButton3_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webLabel10.setText("Month:");
        webLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webLabel11.setText("Year:");
        webLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        webComboBox1_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        webComboBox1_month.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        webComboBox2_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        webComboBox2_year.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(webLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(webComboBox1_agency, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webComboBox1_month, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webComboBox2_year, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(webTextField2_fund_code, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webComboBox2_alot_obj_class_exp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webTextField5_uacs_code, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(webTextField6_allot_rec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(webTextField7_this_rep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(webTextField8_todate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(webButton1_save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(webButton3_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(webButton2_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(webTextField1_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(webPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {webButton1_save, webButton2_cancel, webButton3_update});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {webComboBox1_month, webTextField1_dept});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(webComboBox2_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(webLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(webComboBox1_month, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(webLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webTextField1_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(webComboBox1_agency, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(webLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webTextField2_fund_code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webComboBox2_alot_obj_class_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(webTextField5_uacs_code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(webLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webTextField6_allot_rec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webTextField7_this_rep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webTextField8_todate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(webPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(webButton1_save, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(webButton3_update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webButton2_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {webButton1_save, webButton2_cancel, webButton3_update});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {webComboBox1_agency, webComboBox1_month, webComboBox2_alot_obj_class_exp, webComboBox2_year, webTextField1_dept, webTextField2_fund_code, webTextField5_uacs_code, webTextField6_allot_rec, webTextField7_this_rep, webTextField8_todate});

        setSize(new java.awt.Dimension(1212, 722));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void webButton1_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1_saveActionPerformed
        int unob = Integer.parseInt(webTextField6_allot_rec.getText());
        int todate = Integer.parseInt(webTextField8_todate.getText());
        int total = unob - todate;
        unobligated.setText(String.valueOf(total));
        String SQL_Add_Allot = "Insert into saob_table (year, month, department, agency, fund_code,"
                + " all_obj_class_exp,uacs_code,allot_rec,this_report,to_date,unoblgtd_bal_of_alt)"
                + "values(?,?,?,?,?,?,?,?,?,?,?)";
        
        try {
            pst = (PreparedStatement) conn.prepareStatement(SQL_Add_Allot);
            pst.setString(1, webComboBox2_year.getSelectedItem().toString());
            pst.setString(2, webComboBox1_month.getSelectedItem().toString());
            pst.setString(3, webTextField1_dept.getText());
            pst.setString(4, webComboBox1_agency.getSelectedItem().toString());
            pst.setString(5, webTextField2_fund_code.getText());
            pst.setString(6, webComboBox2_alot_obj_class_exp.getSelectedItem().toString());
            pst.setString(7, webTextField5_uacs_code.getText());
            pst.setString(8, webTextField6_allot_rec.getText());
            pst.setString(9, webTextField7_this_rep.getText());
            pst.setString(10, webTextField8_todate.getText());
            pst.setString(11, unobligated.getText());
            pst.execute();
            Telegraph tel = new Telegraph("Message", "<html>"
                    + "<body style='color:green;font-size:13px'>"
                    + "<b> New Allotment Successfull Saved..."
                    + "</b>"
                    + "</body>"
                    + "</html>", TelegraphType.DOCUMENT_ADD, WindowPosition.TOPRIGHT, 2000);
            TelegraphQueue TQ = new TelegraphQueue();
            TQ.add(tel);
            Table_Pane_Allotments();
            Allotments();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_webButton1_saveActionPerformed

    private void webComboBox2_alot_obj_class_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webComboBox2_alot_obj_class_expActionPerformed
        String Sql_Find_U_Code = "Select * from acct_titles_and_codes where acct_title = ?";
        try {
            pst = (PreparedStatement) conn.prepareStatement(Sql_Find_U_Code);
            pst.setString(1, webComboBox2_alot_obj_class_exp.getSelectedItem().toString());
            rs = pst.executeQuery();
            if (rs.next()) {
                webTextField5_uacs_code.setText(this.rs.getString("u_code"));
                //webTextField15_budget_ofcr_pos.setToolTipText(webTextField15_budget_ofcr_pos.getText());
            } else {
                System.err.print("ERROR");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_webComboBox2_alot_obj_class_expActionPerformed

    private void webButton2_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton2_cancelActionPerformed
        webComboBox2_year.setSelectedIndex(0);
        webComboBox1_month.setSelectedIndex(0);
        webTextField1_dept.setText("");
        webComboBox1_agency.setSelectedIndex(0);
        webTextField2_fund_code.setText("");
        webComboBox2_alot_obj_class_exp.setSelectedIndex(0);
        webTextField5_uacs_code.setText("");
        webTextField6_allot_rec.setText("");
        webTextField7_this_rep.setText("");
        webTextField8_todate.setText("");
        webButton3_update.setEnabled(false);
    }//GEN-LAST:event_webButton2_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAOB_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAOB_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAOB_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAOB_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAOB_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.alee.laf.button.WebButton webButton1_save;
    private com.alee.laf.button.WebButton webButton2_cancel;
    private com.alee.laf.button.WebButton webButton3_update;
    private com.alee.laf.combobox.WebComboBox webComboBox1_agency;
    private com.alee.laf.combobox.WebComboBox webComboBox1_month;
    private com.alee.laf.combobox.WebComboBox webComboBox2_alot_obj_class_exp;
    private com.alee.laf.combobox.WebComboBox webComboBox2_year;
    private com.alee.laf.label.WebLabel webLabel1;
    private com.alee.laf.label.WebLabel webLabel10;
    private com.alee.laf.label.WebLabel webLabel11;
    private com.alee.laf.label.WebLabel webLabel2;
    private com.alee.laf.label.WebLabel webLabel3;
    private com.alee.laf.label.WebLabel webLabel4;
    private com.alee.laf.label.WebLabel webLabel5;
    private com.alee.laf.label.WebLabel webLabel6;
    private com.alee.laf.label.WebLabel webLabel7;
    private com.alee.laf.label.WebLabel webLabel8;
    private com.alee.laf.label.WebLabel webLabel9;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.table.WebTable webTable1_allotment_table;
    private com.alee.laf.text.WebTextField webTextField1_dept;
    private com.alee.laf.text.WebTextField webTextField2_fund_code;
    private com.alee.laf.text.WebTextField webTextField5_uacs_code;
    private com.alee.laf.text.WebTextField webTextField6_allot_rec;
    private com.alee.laf.text.WebTextField webTextField7_this_rep;
    private com.alee.laf.text.WebTextField webTextField8_todate;
    // End of variables declaration//GEN-END:variables

    public void Agencies() {
        String Sql_Find_agncies = "Select * from ors_transaction";
        try {
            pst = (PreparedStatement) conn.prepareStatement(Sql_Find_agncies);
            rs = pst.executeQuery();
            while (rs.next()) {
                // webTextField1_mfo_pap.setText(this.rs.getString("u_code"));
                // webComboBox3_uacs.setModel(new javax.swing.DefaultComboBoxModel(new String[]{ this.rs.getString("u_code")}));
                webComboBox1_agency.addItem(this.rs.getString("agency"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void AOCE_Title() {
        String Sql_Find_Title = "Select * from acct_titles_and_codes";
        try {
            pst = (PreparedStatement) conn.prepareStatement(Sql_Find_Title);
            rs = pst.executeQuery();
            while (rs.next()) {
                // webTextField1_mfo_pap.setText(this.rs.getString("u_code"));
                // webComboBox3_uacs.setModel(new javax.swing.DefaultComboBoxModel(new String[]{ this.rs.getString("u_code")}));
                webComboBox2_alot_obj_class_exp.addItem(this.rs.getString("acct_title"));
            }
        } catch (Exception e) {
        }
    }
    
    public void Table_Pane_Allotments() {
        
        for (int i = 0; i < webTable1_allotment_table.getColumnCount(); i++) {
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) webTable1_allotment_table.getColumnModel();
            TableColumn col = colModel.getColumn(i);
            int width = 500;
            
            TableCellRenderer renderer = col.getHeaderRenderer();
            for (int r = 0; r < webTable1_allotment_table.getRowCount(); r++) {
                renderer = webTable1_allotment_table.getCellRenderer(r, i);
                Component comp = renderer.getTableCellRendererComponent(webTable1_allotment_table, webTable1_allotment_table.getValueAt(r, i),
                        false, false, r, i);
                width = Math.max(width, comp.getPreferredSize().width);
            }
            
            col.setPreferredWidth(width + 400);
            col.setMaxWidth(width);
            col.setWidth(width);
        }
    }
    
    public void Allotments() {
        String show_allot = "Select id as 'ID', year as 'Year', month as 'Month', department as 'Department',"
                + "agency as 'Agency', fund_code as 'Fund Code', all_obj_class_exp as 'Allotment Object Class of Expenditures',"
                + "uacs_code as 'Uacs Code', allot_rec as 'Allotment Received', this_report as 'This Report', to_date as 'To Date',"
                + "unoblgtd_bal_of_alt as 'Unobligated Balance of Allotment' from saob_table";
        try {
            pst = (PreparedStatement) conn.prepareStatement(show_allot);
            rs = pst.executeQuery();
            webTable1_allotment_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
